import React from "react"
import { graphql, useStaticQuery } from "gatsby"

import Accordion from "@material-ui/core/Accordion"
import AccordionSummary from "@material-ui/core/AccordionSummary"
import AccordionDetails from "@material-ui/core/AccordionDetails"
import Typography from "@material-ui/core/Typography"
import ExpandMoreIcon from "@material-ui/icons/ExpandMore"

import * as roadmapStyles from "./roadmap.module.scss"

const Roadmap = () => {
  const data = useStaticQuery(graphql`
    query {
      site {
        siteMetadata {
          discordUrl
          twitterUrl
          telegramUrl
        }
      }
    }
  `)

  return (
    <div className={roadmapStyles.roadmap}>
      <h2 id="roadmap" className={roadmapStyles.h2}>
        Roadmap
      </h2>
      <ol className={roadmapStyles.ol}>
        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            style={{ backgroundColor: "#eee" }}
          >
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                fontSize: "1.25em",
              }}
            >
              <li className={roadmapStyles.li}>
                <s>Design and mint 10,000 Zombits</s>{" "}
                <span className={roadmapStyles.light}>April 2021</span>
              </li>
            </Typography>
          </AccordionSummary>

          <AccordionDetails style={{ backgroundColor: "#fff" }}>
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                margin: "auto",
              }}
            >
              <p>
                10,000 Zombits were algorithmically generated by combining five
                pseudo-random features: head, eyes, mouth, suit, and skin.
              </p>
              <p>
                Each combination resulted in a unique Zombit design, which were
                pre-minted on the Cardano blockchain using some
                pre-smart-contract magic.
              </p>
              <p>
                You can explore all Zombits with the{" "}
                <a href="/#explore">Zombit Explorer</a>.
              </p>
            </Typography>
          </AccordionDetails>
        </Accordion>
        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            style={{ backgroundColor: "#eee" }}
          >
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                fontSize: "1.25em",
              }}
            >
              <li className={roadmapStyles.li}>
                <s>Create social media presence</s>{" "}
                <span className={roadmapStyles.light}>
                  April&ndash;August 2021
                </span>
              </li>
            </Typography>
          </AccordionSummary>
          <AccordionDetails style={{ backgroundColor: "#fff" }}>
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                margin: "auto",
              }}
            >
              <p>
                We didn't stop there! We knew we had to become more present on
                social media to get our Zombits out to the world.
              </p>
              <p>
                We worked tirelessly to build a following on platforms like{" "}
                <a
                  href={data.site.siteMetadata.discordUrl}
                  target="_blank"
                  rel="noreferrer"
                >
                  Discord
                </a>
                ,{" "}
                <a
                  href={data.site.siteMetadata.twitterUrl}
                  target="_blank"
                  rel="noreferrer"
                >
                  Twitter
                </a>
                , and{" "}
                <a
                  href={data.site.siteMetadata.telegramUrl}
                  target="_blank"
                  rel="noreferrer"
                >
                  Telegram
                </a>{" "}
                to validate the project and grow as a community.
              </p>
            </Typography>
          </AccordionDetails>
        </Accordion>
        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            style={{ backgroundColor: "#eee" }}
          >
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                fontSize: "1.25em",
              }}
            >
              <li className={roadmapStyles.li}>
                <s>🚀 Launch Zombits</s>{" "}
                <span className={roadmapStyles.light}>29 August 2021</span>
              </li>
            </Typography>
          </AccordionSummary>
          <AccordionDetails style={{ backgroundColor: "#fff" }}>
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                margin: "auto",
              }}
            >
              <p>
                On 29 August 2021 at 5pm EST, Zombits launched. Almost all
                10,000 NFTs were sold out in 22 minutes!
              </p>
              <p>
                Fun fact! Due to technical difficulties, we had to send out all
                sold Zombits semi-manually over the following 24 hours.
              </p>
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            style={{ backgroundColor: "#eee" }}
          >
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                fontSize: "1.25em",
              }}
            >
              <li className={roadmapStyles.li}>
                <s>Design 10,000 Humbits</s>{" "}
                <span className={roadmapStyles.light}>October 2021</span>
              </li>
            </Typography>
          </AccordionSummary>
          <AccordionDetails style={{ backgroundColor: "#fff" }}>
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                margin: "auto",
              }}
            >
              <p>
                The journey of Zombits shall continue! We're introducing 10,000
                Humbit NFTs, each designed with its unique set of traits.
              </p>
              <p>
                Why, you ask? Humbits will play a crucial role in the upcoming{" "}
                <i>Humbits vs. Zombits</i> game; some Humabits will have
                different in-game abilities than others.
              </p>
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            style={{ backgroundColor: "#eee" }}
          >
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                fontSize: "1.25em",
              }}
            >
              <li className={roadmapStyles.li}>
                <s>🚀 Launch Humbits</s>{" "}
                <span className={roadmapStyles.light}>October 2021</span>
              </li>
            </Typography>
          </AccordionSummary>
          <AccordionDetails style={{ backgroundColor: "#fff" }}>
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                margin: "auto",
              }}
            >
              <p>
                The Humbits are preparing for war, and will drop this Sunday
                (October 17th) at 5pm EST!
              </p>
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            style={{ backgroundColor: "#eee" }}
          >
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                fontSize: "1.25em",
              }}
            >
              <li className={roadmapStyles.li}>
                Develop Humbits vs. Zombits game{" "}
                <span className={roadmapStyles.light}>
                  October&ndash;November 2021
                </span>
              </li>
            </Typography>
          </AccordionSummary>
          <AccordionDetails style={{ backgroundColor: "#fff" }}>
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                margin: "auto",
              }}
            >
              <p>Let the development begin!</p>
              <p>
                We'll be busy designing the game and writing Cardano smart
                contracts to get our <i>Humbits vs. Zombits</i> game onto the
                Cardano blockchain.
              </p>
              <p>
                The game will have a rock-paper-scissors style gameplay (think
                Pokémon battles). A Zombit owner will be paired up with a
                Humbits owner randomly, and each player will be assigned three
                random weapons. The players will choose which weapon they want
                to use against their opponent, and the winner with stronger
                weapon wins.
              </p>
              <p>
                Players will receive certain benefits throughout the game based
                on the players' rarity, so rarer Zombits/Humbits may have more
                of an advantage.
              </p>
              <p>
                Players will need to place ADA bets before participating in the
                game. Bets from the loser will be transferred to the winner.
              </p>
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            style={{ backgroundColor: "#eee" }}
          >
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                fontSize: "1.25em",
              }}
            >
              <li className={roadmapStyles.li}>
                🚀 Launch Humbits vs. Zombits game{" "}
                <span className={roadmapStyles.light}>November 2021</span>
              </li>
            </Typography>
          </AccordionSummary>
          <AccordionDetails style={{ backgroundColor: "#fff" }}>
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                margin: "auto",
              }}
            >
              <p>
                Once development of the game is done and tested, we'll launch it
                on the Cardano blockchain.
              </p>
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            style={{ backgroundColor: "#eee" }}
          >
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                fontSize: "1.25em",
              }}
            >
              <li className={roadmapStyles.li}>
                🚀 Launch Zombits stake pool{" "}
                <span className={roadmapStyles.light}>December 2021</span>
              </li>
            </Typography>
          </AccordionSummary>
          <AccordionDetails style={{ backgroundColor: "#fff" }}>
            <Typography
              style={{
                fontFamily:
                  "Connection III, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji",
                margin: "auto",
              }}
            >
              <p>
                Probably not last, and definitely not least &mdash; the Zombits
                stake pool!
              </p>
              <p>
                May or may not have a lottery system, where prizes (ADA or NFTs)
                are distributed to delegators randomly (in addition to their
                rewards)...
              </p>
              <p>
                Rewards from pool operation may or many not be used to fund
                giveaways, lotteries, tournaments, etc...
              </p>
              <p>...no promises, TBD. 👀</p>
            </Typography>
          </AccordionDetails>
        </Accordion>
      </ol>
      <p>More to come... Stay tuned for announcements!</p>
      <p>
        <span className={roadmapStyles.light}>Subject to change</span>
      </p>
    </div>
  )
}

export default Roadmap
